import { isIterable } from './isIterable.js'

/**
 * Test whether the {@link predicate} holds for at least one value generated by the {@link source}
 *
 * The source will be consumed in the process.
 *
 * @example
 * some([false, true, false]); // returns true
 * @example
 * some([3, 5, 7], (n) => n % 2 === 0); // returns false
 *
 * @requires module:itertools.isIterable
 *
 * @template T
 * @param {Iterable<T>} source where to take the values from
 * @param {Predicate<T>} [predicate=Boolean] a function to test each value
 * @returns {boolean} true if one value matches the predicate, otherwise false
 *
 * @throws {TypeError} when {@link source} is not an {@link Iterable}
 * @throws {TypeError} when {@link predicate} is not an function
 */
export function some (source, predicate = Boolean) {
  if (!isIterable(source)) {
    throw new TypeError(`Argument 'source' should be iterable, received ${source} (${typeof source}).`)
  }

  for (const element of source) {
    if (predicate(element)) {
      return true
    }
  }
  return false
}
